electron/remote

src/common/get-electron-binding.ts
src/main/objects-registry.ts
src/main/server.ts
src/renderer/callbacks-registry.ts
src/renderer/remote.ts

Fixes #15.
This was broken with https://github.com/electron/electron/pull/24191 when
`process.electronBinding` was removed.

fix: use _linkedBinding when electronBinding not available

---

src/renderer/remote.ts

Leaked `ipcRenderer.sendTo()` can be used to send messages, which are expected to come from the main process.

fix: ensure that messages are sent from the main process

---

src/common/module-names.ts
src/common/type-utils.ts
src/internal-ambient.d.ts
src/main/server.ts
src/renderer/remote.ts

The following changes are mirroring code in Electron core
- [module names as array](https://github.com/electron/electron/blob/4f2490f8b80683dd115f851d84b123e854e32e43/lib/browser/api/module-names.ts#L7-L40)
- [desktopCapturer only when enabled](https://github.com/electron/electron/blob/4f2490f8b80683dd115f851d84b123e854e32e43/lib/browser/api/module-names.ts#L42-L44)
- chore: remove bunch of usages of any [#27512](https://github.com/electron/electron/pull/27512)

refactor: module list array, import nativeImage, type safety improvements

---

src/internal-ambient.d.ts
src/renderer/remote.ts

`process._linkedBinding()` / `process.electronBinding()` are not available in sandboxed renderers

refactor: don't use command_line binding

---

index.d.ts
package.json

I noticed that the file defined in `main` in the `package.json` file doesn't have type declarations since it is written in JavaScript.
This fix might help with https://github.com/electron/remote/issues/35.

fix: Add main type declarations

---

src/common/get-electron-binding.ts
src/common/module-names.ts
src/internal-ambient.d.ts
src/renderer/remote.ts

- Use `process.contextId` added by https://github.com/electron/electron/pull/28007 to avoid using `v8_util` binding
- Enable all Electron modules when `features` binding cannot be used
Closes #42.

feat: add support for running in sandboxed renderers

---

tsconfig.json

Currently the tests are failing on main because `tsc` can't be properly executed. Since we don't need to build the `index.d.ts` file, we can just exclude it and it will be published as it is.
cc @nornagon

fix: Exclude index.d.ts from tsconfig

---

index.d.ts
main/index.d.ts
renderer/index.d.ts
tsconfig.json

This fixes https://github.com/electron/remote/issues/52.
This fixes https://github.com/electron/remote/issues/60.
cc @nornagon

fix: Export types from main and renderer, fix main types

---

docs/migration-2.md

This adds a migration guide from 1.x => 2.x. See https://github.com/electron/remote/pull/72#issuecomment-914466765
Ref #72.

docs: add 2.x migration guide

---

README.md
src/main/index.ts
src/main/server.ts

BREAKING CHANGE: This removes the `enableRemoteModule` option in favor of a new `.enable()` method for enabling the remote module on a particular WebContents. See https://github.com/electron/remote/blob/main/docs/migration-2.md for migration instructions.
Fixes #71

fix!: change enableRemoteModule to .enable() for electron@14

---

src/main/server.ts

no need to check electron verison in 2.x
https://github.com/electron/remote/issues/76

fix: remove electron version check in 2.x version

---

docs/migration-2.md

Added `.initialize()` in migration-v2 guide. I am doing this PR because the guide on whether to keep that line of code or not was not very clear, also because that line is not even mentioned in migration-v2, making the developer think to remove it. (ref. #79 )

docs: add .initialize() to avoid users removing it

---

.circleci/config.yml
.gitignore
package.json
src/internal-ambient.d.ts
test/all.ts
yarn.lock

I have to say it is a bit of a joke a new major version is released which focuses on `electron>=14`, but it is not tested with it.
So I made some changes so that electron 11-15 is tested. To get electron 12/13 working `contextIsolation` needed to be disabled.
Electron 14/15 is not working yet, I am working on that. I am not sure I will succeed, but I will open a separate PR for that.

test: Test multiple electron versions

---

tsconfig.json

To prevent errors like this when running `tsc` twice:
`error TS5055: Cannot write file '/home/anders/electron/remote/dist/src/common/get-electron-binding.d.ts' because it would overwrite input file.`

fix: Exclude dist in tsconfig.json

---

src/main/server.ts
test/all.ts

In TypeScript 4.4, `--strict` [implies](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables) `--useUnknownInCatchVariables`, so in a `catch (error)` block, `error` has type `unknown` rather than `any`.

Make catch clauses compatible with TypeScript 4.4

---

.circleci/config.yml
src/main/server.ts
src/renderer/remote.ts
test/all.ts

A big section of the test suite has actually been testing the builtin `electron.remote` rather than this module. Correcting that reveals two bugs.
* The protection of the `Promise` global from electron/electron#20925 has been lost. Adding that back fixes the test.
* The GC race test originating at electron/electron#24087 fails due to an incorrectly deleted semicolon. Adding a semicolon fixes the test.

Test this module, not the builtin electron.remote; test with Electron 14, 15, 16, and 17

---

package.json

To allow installation directly from GitHub (e.g. `npm i electron/remote#main`).

Rename prepublishOnly script to prepare; add {main,renderer}/index.d.ts to package

---

index.d.ts

Allows TypeScript to easily access SafeStorage.
e.g 
``` TypeScript
import { app, safeStorage } from "@electron/remote";
```
afterwards it is accessible by 
``` TypeScript
if (safeStorage.isEncryptionAvailable()) {
console.log("Encryption is available");
}
```

fix: add TypeScript interface for SafeStorage

---

index.d.ts

This reverts commit 2f79ed6b6cb68e45328e914f643bddb86102622a.
Unfortunately CircleCI tests weren't run on #155 (this has been fixed now) so it wasn't noticed that the change broke tests on older Electron versions where `SafeStorage` isn't implemented. I explored various ways to try to make this conditional if possible, but there's no clean solution that I'm aware of. Let's revert this so that it doesn't break compatibility with older Electron versions.

revert: "Adds TypeScript interface for SafeStorage (#155)"

---

src/common/module-names.ts

Refs https://github.com/electron/remote/pull/154
See https://github.com/electron/remote/pull/154#issuecomment-1752156161:
When `features` no longer contains `isDesktopCapturerEnabled`, `!features.isDesktopCapturerEnabled` evaluates to true, which then means the conditional checks the third condition: `features.isDesktopCapturerEnabled()` which throws an error:
```
Uncaught TypeError: features.isDesktopCapturerEnabled is not a function
```

fix: `features.isDesktopCapturerEnabled` error

---

src/main/index.ts
src/main/server.ts

This change adds the "isInitialized" function
Now it is impossible to check whether initialization has been performed. This may cause errors when using modules that also use electron/remote.
Current code (so that it does not throw an error if initialization has already been done):
```js
try { remote.initialize(); } catch { }
```
New code:
```js
if (!remote.isInitialized()) {
remote.initialize();
}
```

feat: add isInitialized

---

yarn.lock

We ran `uuaw --audit` and it resulted in a clean yarn audit.
```
Attempting to fix advisory: GHSA-gxpj-cx7g-858c - Regular Expression Denial of Service in debug
Scanning dependency chain:
electron --> @electron/get --> sumchecker --> debug
[1/9] Trying from: debug@^4.1.0
Resolving: debug@^4.1.0 --> 4.3.4
[1/9] Updating chain to latest starting at: debug@^4.1.0 results in a patched version: debug@4.3.4
[1/9] Running yarn install now
Attempting to fix advisory: GHSA-gxpj-cx7g-858c - Regular Expression Denial of Service in debug
Scanning dependency chain:
electron --> @electron/get --> debug
[1/8] Trying from: debug@^4.1.1
Resolving: debug@^4.1.1 --> 4.3.4
[1/8] Updating chain to latest starting at: debug@^4.1.1 results in a patched version: debug@4.3.4
[1/8] Running yarn install now …
```

build: update yarn.lock to fix audit output

---

.circleci/config.yml
src/main/server.ts
src/renderer/remote.ts
test/all.ts

Since the property has been removed with Electron 28

fix: senderId removed in Electron 28

---

src/common/module-names.ts

ref https://github.com/electron/remote/commit/168b4677049be317ae3788748544f4cb3d73625d
Same deal but for `isViewApiEnabled`. Should fix `@electron/remote` for Electron 29. Closes #179.

fix: optional isViewApiEnabled call

---

.github/workflows/test.yml

`ubuntu-latest` is now Ubuntu 24.04 and CI is now failing due to the sandboxing changes with running Electron. To unblock CI here for now, revert to Ubuntu 22.04 until a proper solution can be implemented.

ci: revert runner to Ubuntu 22.04

---

.github/workflows/test.yml

Not sure why, but there's a consistent failure in CI runs for this repo where the Electron v25 run hangs until it's killed by the timeout. Sometimes rerunning it can get a green run, but seems like 80% of the time it hangs, and it's always v25.
Since it's an unsupported version of Electron anyway, skip it so that we don't have consistent test failures.

ci: skip Electron 25

---

.github/workflows/test.yml
src/common/module-names.ts

This was added in E35. Expands the test matrix Electron versions and also disables `fail-fast` so the full matrix is run even if there are failures.

fix: add ServiceWorkerMain module
